import Foundation

public enum CleanupConfidenceLevel: String, Codable, CaseIterable, Identifiable {
    case high = "High confidence"
    case reviewRequired = "Review required"

    public var id: String { rawValue }
}

public enum CleanupEvidencePolicy {
    public static let measurementBasis = "Measured during the latest full storage scan. Group totals include every byte below the selected root path."

    public static let restoreBehavior = "App Monitor moves the selected root to quarantine and records its original path. Restore moves it back while the quarantine copy remains available."

    public static func confidence(for category: StorageCategory) -> CleanupConfidenceLevel {
        switch category {
        case .caches, .logs, .httpStorages, .savedApplicationState, .diagnosticReports:
            return .high
        case .applicationSupport, .extensions, .launchAgents, .applicationScripts, .webKit, .cookies,
             .bundle, .containers, .groupContainers, .preferences:
            return .reviewRequired
        }
    }

    public static func confidence(
        for category: StorageCategory,
        path: String,
        app: MonitoredApp
    ) -> CleanupConfidenceLevel {
        if isDeveloperCache(path: path) || isSystemApplication(app) || isICloudAssociated(path: path) {
            return .reviewRequired
        }
        return confidence(for: category)
    }

    public static func confidenceRationale(for category: StorageCategory) -> String {
        switch category {
        case .caches, .logs, .httpStorages, .savedApplicationState, .diagnosticReports:
            return "This category is normally regenerated by the owning app. App Monitor still quarantines it first so the change remains reversible."
        case .applicationSupport, .extensions, .launchAgents, .applicationScripts, .webKit, .cookies:
            return "This path can contain durable app state or behavior. It is suggested only after at least 30 days without app activity and requires review."
        case .bundle, .containers, .groupContainers, .preferences:
            return "This category can contain the app, settings, or durable user data, so cleanup suggestions never select it automatically."
        }
    }

    public static func isProtectedFromCleanupSuggestion(_ category: StorageCategory) -> Bool {
        switch category {
        case .bundle, .containers, .groupContainers, .preferences:
            return true
        case .applicationSupport, .caches, .savedApplicationState, .httpStorages, .logs,
             .extensions, .launchAgents, .applicationScripts, .webKit, .cookies, .diagnosticReports:
            return false
        }
    }

    public static func isProtectedFromCleanupSuggestion(
        category: StorageCategory,
        path: String,
        app: MonitoredApp
    ) -> Bool {
        isProtectedFromCleanupSuggestion(category)
            || isSystemApplication(app)
            || isICloudAssociated(path: path)
    }

    public static func rebuildability(for category: StorageCategory, path: String) -> String {
        if isDeveloperCache(path: path) {
            return "Usually rebuildable by developer tools, but rebuilding can be expensive and the path requires explicit review."
        }
        switch confidence(for: category) {
        case .high:
            return "Normally regenerated by the owning app or macOS."
        case .reviewRequired:
            return "May contain durable app state; rebuildability is not assumed."
        }
    }

    public static func appliedExclusions(category: StorageCategory, path: String, app: MonitoredApp) -> String {
        var exclusions: [String] = []
        if isSystemApplication(app) { exclusions.append("system application") }
        if isICloudAssociated(path: path) { exclusions.append("iCloud-associated data") }
        if isProtectedFromCleanupSuggestion(category) { exclusions.append("protected \(category.rawValue.lowercased()) category") }
        if isDeveloperCache(path: path) { exclusions.append("developer cache requires review") }
        return exclusions.isEmpty ? "No protected-path exclusion matched" : exclusions.joined(separator: ", ")
    }

    public static func isSystemApplication(_ app: MonitoredApp) -> Bool {
        let path = app.path.standardizedCleanupPath
        return path.hasPrefix("/system/applications/")
            || path == "/system/applications"
            || app.bundleIdentifier?.lowercased().hasPrefix("com.apple.") == true
    }

    public static func isICloudAssociated(path: String) -> Bool {
        let path = path.standardizedCleanupPath
        return path.contains("/mobile documents/")
            || path.contains("/library/cloudstorage/")
            || path.contains("/icloud drive/")
            || path.contains("/clouddocs/")
            || path.contains("/ubiquity/")
    }

    public static func isDeveloperCache(path: String) -> Bool {
        let path = path.standardizedCleanupPath
        return path.contains("/library/developer/")
            || path.contains("/deriveddata/")
            || path.contains("/archives/")
            || path.contains("/coreSimulator/")
    }

    public static func exclusionReason(for category: StorageCategory) -> String? {
        guard isProtectedFromCleanupSuggestion(category) else { return nil }
        switch category {
        case .bundle:
            return "Application bundles are never included in automatic cleanup suggestions."
        case .preferences:
            return "Preferences are protected because they contain durable user settings."
        case .containers, .groupContainers:
            return "Containers are protected because they can contain durable user data shared with the app or its extensions."
        default:
            return nil
        }
    }
}

private extension String {
    var standardizedCleanupPath: String {
        (self as NSString).standardizingPath.lowercased()
    }
}
